apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: hypernova-439518

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-host-secret
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: db-host-k8s-secret
  data:
    - secretKey: host
      remoteRef:
        key: db-host

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-user-secret
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: db-user-k8s-secret
  data:
    - secretKey: user
      remoteRef:
        key: db-user

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-password-secret
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: db-password-k8s-secret
  data:
    - secretKey: password
      remoteRef:
        key: db-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-name-secret
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: db-name-k8s-secret
  data:
    - secretKey: name
      remoteRef:
        key: db-name

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-key-secret
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: secret-key-k8s-secret
  data:
    - secretKey: secret
      remoteRef:
        key: secret-key
