apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee-shop
  template:
    metadata:
      labels:
        app: coffee-shop
    spec:
      containers:
      - name: barista-coffee-app
        image: gcr.io/${{ vars.GCP_PROJECT_ID }}/coffee-shop:$IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: "projects/${{ vars.GCP_PROJECT_ID }}/secrets/db-host/versions/latest"
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: "projects/${{ vars.GCP_PROJECT_ID }}/secrets/db-user/versions/latest"
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "projects/${{ vars.GCP_PROJECT_ID }}/secrets/db-password/versions/latest"
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: "projects/${{ vars.GCP_PROJECT_ID }}/secrets/db-name/versions/latest"
              key: name
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "projects/${{ vars.GCP_PROJECT_ID }}/secrets/secret-key/versions/latest"
              key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-shop
spec:
  type: LoadBalancer
  selector:
    app: coffee-shop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
