name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from barista-app-docker repository
      uses: actions/checkout@v3
      with:
        repository: shonevarkey/barista-app-docker
        ref: main

    - name: Checkout code from gcp-github-actions-gke-pipeline repository
      uses: actions/checkout@v3
      with:
        repository: shonevarkey/gcp-github-actions-gke-pipeline
        ref: main
        path: gcp-github-actions-gke-pipeline

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker with Google Container Registry
      run: gcloud auth configure-docker gcr.io

    - name: Build and Push Docker Image with Commit Hash Tagging
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/coffee-shop:$IMAGE_TAG .
        docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/coffee-shop:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Configure kubectl
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
        location: ${{ vars.GKE_CLUSTER_REGION }}
    
    - name: Update Image Tag in Kubernetes Manifest
      run: |
        sed -i "s|gcr.io/${{ vars.GCP_PROJECT_ID }}/coffee-shop:latest|gcr.io/${{ vars.GCP_PROJECT_ID }}/coffee-shop:$IMAGE_TAG|g" ./gcp-github-actions-gke-pipeline/kubernetes-manifests/k8s-manifests.yaml
        sed -i "s|projects/${{ vars.GCP_PROJECT_ID }}|projects/${{ vars.GCP_PROJECT_ID }}|g" ./gcp-github-actions-gke-pipeline/kubernetes-manifests/k8s-manifests.yaml

    - name: Deploy to GKE
      run: |
        echo "Deploying to GKE..."
        kubectl apply -f gcp-github-actions-gke-pipeline/kubernetes-manifests/k8s-manifests.yaml
        kubectl rollout status deployment/coffee-shop
