name: Deploy to GKE

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for Workload Identity Federation
  contents: read    # Required for actions/checkout

# env:
#  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from barista-app-docker repository
      uses: actions/checkout@v3
      with:
        repository: shonevarkey/barista-app-docker
        ref: main

    - name: Checkout code from gcp-github-actions-gke-pipeline repository
      uses: actions/checkout@v3
      with:
        repository: shonevarkey/gcp-github-actions-gke-pipeline
        ref: main
        path: gcp-github-actions-gke-pipeline

    - name: Authenticate with GCP using using Workload Identity Federation
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/462743718191/locations/global/workloadIdentityPools/my-pool/providers/github-provider"
        service_account: "github-actions-sa@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

    - name: Authenticate Docker with Google Container Registry
      run: |
        gcloud auth configure-docker gcr.io --quiet
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io

    - name: Build and Push Docker Image with Commit Hash Tagging
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/coffee-shop:$IMAGE_TAG .
        docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/coffee-shop:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Configure kubectl
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
        location: ${{ vars.GKE_CLUSTER_REGION }}
    
    - name: Update Image Tag in Kubernetes Manifest
      run: |
        sed -i "s|gcr.io/${GCP_PROJECT_ID}/coffee-shop:latest|gcr.io/${GCP_PROJECT_ID}/coffee-shop:$IMAGE_TAG|g" ./gcp-github-actions-gke-pipeline/kubernetes-manifests/k8s-manifests.yaml

    - name: Check Updated Kubernetes Manifest
      run: |
        cat ./gcp-github-actions-gke-pipeline/kubernetes-manifests/k8s-manifests.yaml
        echo "######## Secret Variables ##########"
        echo "GCP Project ID = ${{ secrets.GCP_PROJECT_ID }}" > project.yaml | cat project.yaml
        echo "GKE_CLUSTER_NAME = ${{ secrets.GKE_CLUSTER_NAME }}" > name.yaml | cat name.yaml
        echo "GKE_CLUSTER_REGION = ${{ secrets.GKE_CLUSTER_REGION }}" > region.yaml | cat region.yaml
        echo "######## Environment Variables ##########"
        echo "GCP Project ID = ${{ vars.GCP_PROJECT_ID }}" > vproject.yaml | cat vproject.yaml
        echo "GKE_CLUSTER_NAME = ${{ vars.GKE_CLUSTER_NAME }}" > vname.yaml| cat vname.yaml
        echo "GKE_CLUSTER_REGION = ${{ vars.GKE_CLUSTER_REGION }}" > vregion.yaml| cat vregion.yaml

    
    #- name: Deploy to GKE
    #  run: |
    #    echo "Deploying to GKE..."
    #    kubectl apply -f gcp-github-actions-gke-pipeline/kubernetes-manifests/k8s-manifests.yaml
    #    kubectl apply -f gcp-github-actions-gke-pipeline/kubernetes-manifests/external-secrets.yaml
    #    kubectl rollout status deployment/coffee-shop
